sd_card/diskio.h File Reference
#include `integer.h`
*
Macros
#define STA_NOINIT 0x01	/* Drive not initialized */
#define STA_NODISK 0x02	/* No medium in the drive */
#define STA_PROTECT 0x04	/* Write protected */
#define CTRL_SYNC 0	/* Flush disk cache (for write functions) */
#define GET_SECTOR_COUNT 1	/* Get media size (for only f_mkfs()) */
#define GET_BLOCK_SIZE 3	/* Get erase block size (for only f_mkfs()) */
#define CTRL_ERASE_SECTOR 4	/* Force erased a block of sectors (for only _USE_ERASE) */
#define CTRL_POWER 5	/* Get/Set power status */
#define MMC_GET_TYPE 10	/* Get card type */
#define MMC_GET_CSD 11	/* Get CSD */
#define MMC_GET_CID 12	/* Get CID */
#define MMC_GET_OCR 13	/* Get OCR */
#define MMC_GET_SDSTAT 14	/* Get SD status */
#define ATA_GET_REV 20	/* Get F/W revision */
#define ATA_GET_MODEL 21	/* Get model name */
#define ATA_GET_SN 22	/* Get serial number */
#define CT_MMC 0x01		/* MMC ver 3 */
#define CT_SD1 0x02		/* SD ver 1 */
#define CT_SD2 0x04		/* SD ver 2 */
#define CT_SDC (CT_SD1|CT_SD2)	/* SD */
#define CT_BLOCK 0x08		/* Block addressing */
Typedefs
typedef BYTE DSTATUS
Enumerations
enum DRESULT {
*
RES_OK = 0,
RES_ERROR,
RES_WRPRT,
RES_NOTRDY,
*
RES_PARERR
 }
Functions
DSTATUS disk_initialize (BYTE pdrv)
DSTATUS disk_status (BYTE pdrv)
DRESULT disk_read (BYTE pdrv, BYTE *buff, DWORD sector, BYTE count)
DRESULT disk_write (BYTE pdrv, const BYTE *buff, DWORD sector, BYTE count)
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void *buff)
Macro Definition Documentation
#define ATA_GET_MODEL 21	/* Get model name */
#define ATA_GET_REV 20	/* Get F/W revision */
#define ATA_GET_SN 22	/* Get serial number */
#define CT_BLOCK 0x08		/* Block addressing */
Referenced by disk_initialize(), disk_read(), and disk_write().
#define CT_MMC 0x01		/* MMC ver 3 */
Referenced by disk_initialize().
#define CT_SD1 0x02		/* SD ver 1 */
Referenced by disk_initialize().
#define CT_SD2 0x04		/* SD ver 2 */
Referenced by disk_initialize().
#define CT_SDC (CT_SD1|CT_SD2)	/* SD */
Referenced by disk_write().
#define CTRL_ERASE_SECTOR 4	/* Force erased a block of sectors (for only _USE_ERASE) */
Referenced by remove_chain().
#define CTRL_POWER 5	/* Get/Set power status */
#define CTRL_SYNC 0	/* Flush disk cache (for write functions) */
Referenced by disk_ioctl(), and sync_fs().
#define GET_BLOCK_SIZE 3	/* Get erase block size (for only f_mkfs()) */
Referenced by disk_ioctl().
#define GET_SECTOR_COUNT 1	/* Get media size (for only f_mkfs()) */
Referenced by disk_ioctl().
#define MMC_GET_CID 12	/* Get CID */
#define MMC_GET_CSD 11	/* Get CSD */
#define MMC_GET_OCR 13	/* Get OCR */
#define MMC_GET_SDSTAT 14	/* Get SD status */
#define MMC_GET_TYPE 10	/* Get card type */
#define STA_NODISK 0x02	/* No medium in the drive */
#define STA_NOINIT 0x01	/* Drive not initialized */
Referenced by chk_mounted(), disk_initialize(), disk_ioctl(), disk_read(), disk_status(), disk_write(), and validate().
#define STA_PROTECT 0x04	/* Write protected */
Referenced by chk_mounted().
Typedef Documentation
typedef BYTE DSTATUS
Enumeration Type Documentation
enum DRESULT
Enumerator
RES_OK
RES_ERROR
RES_WRPRT
RES_NOTRDY
RES_PARERR
Function Documentation
DSTATUS disk_initialize (BYTE pdrv)
References ACMD41, CardType, CK_INIT, CK_L, CMD0, CMD1, CMD16, CMD58, CMD8, CS_H, CS_INIT, CT_BLOCK, CT_MMC, CT_SD1, CT_SD2, deselect(), DI_INIT, dly_us(), DO_INIT, rcvr_mmc(), RES_NOTRDY, send_cmd(), STA_NOINIT, and Stat.
Referenced by chk_mounted().
DRESULT disk_ioctl (BYTE pdrv, BYTE cmd, void * buff)
References CMD9, CTRL_SYNC, deselect(), disk_status(), GET_BLOCK_SIZE, GET_SECTOR_COUNT, rcvr_datablock(), RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, select(), send_cmd(), and STA_NOINIT.
Referenced by chk_mounted(), remove_chain(), and sync_fs().
DRESULT disk_read (BYTE pdrv, BYTE * buff, DWORD sector, BYTE count)
References CardType, CMD12, CMD17, CMD18, CT_BLOCK, deselect(), disk_status(), rcvr_datablock(), RES_ERROR, RES_NOTRDY, RES_OK, send_cmd(), and STA_NOINIT.
Referenced by check_fs(), chk_mounted(), f_lseek(), f_read(), f_write(), and move_window().
DSTATUS disk_status (BYTE pdrv)
References STA_NOINIT, and Stat.
Referenced by chk_mounted(), disk_ioctl(), disk_read(), disk_write(), and validate().
DRESULT disk_write (BYTE pdrv, const BYTE * buff, DWORD sector, BYTE count)
References ACMD23, CardType, CMD24, CMD25, CT_BLOCK, CT_SDC, deselect(), disk_status(), RES_ERROR, RES_NOTRDY, RES_OK, send_cmd(), STA_NOINIT, and xmit_datablock().
Referenced by f_lseek(), f_read(), f_sync(), f_write(), sync_fs(), and sync_window().