sd_card/ff.c File Reference
#include `ff.h`
*
#include `diskio.h`
*
Macros
#define SS(fs) 512U			/* Fixed sector size */
#define ENTER_FF(fs)
#define LEAVE_FF(fs, res) return res
#define ABORT(fs, res) { fp->flag |= FA__ERROR; LEAVE_FF(fs, res); }
#define _DF1S 0
#define _EXCVT
#define IsUpper(c) (((c)>='A')&&((c)<='Z'))
#define IsLower(c) (((c)>='a')&&((c)<='z'))
#define IsDigit(c) (((c)>='0')&&((c)<='9'))
#define IsDBCS1(c) 0
#define IsDBCS2(c) 0
#define NS 11		/* Index of name status byte in fn[] */
#define NS_LOSS 0x01	/* Out of 8.3 format */
#define NS_LFN 0x02	/* Force to create LFN entry */
#define NS_LAST 0x04	/* Last segment */
#define NS_BODY 0x08	/* Lower case flag (body) */
#define NS_EXT 0x10	/* Lower case flag (ext) */
#define NS_DOT 0x20	/* Dot entry */
#define MIN_FAT16 4086	/* Minimum number of clusters for FAT16 */
#define MIN_FAT32 65526	/* Minimum number of clusters for FAT32 */
#define BS_jmpBoot 0	/* Jump instruction (3) */
#define BS_OEMName 3	/* OEM name (8) */
#define BPB_BytsPerSec 11	/* Sector size [byte] (2) */
#define BPB_SecPerClus 13	/* Cluster size [sector] (1) */
#define BPB_RsvdSecCnt 14	/* Size of reserved area [sector] (2) */
#define BPB_NumFATs 16	/* Number of FAT copies (1) */
#define BPB_RootEntCnt 17	/* Number of root dir entries for FAT12/16 (2) */
#define BPB_TotSec16 19	/* Volume size [sector] (2) */
#define BPB_Media 21	/* Media descriptor (1) */
#define BPB_FATSz16 22	/* FAT size [sector] (2) */
#define BPB_SecPerTrk 24	/* Track size [sector] (2) */
#define BPB_NumHeads 26	/* Number of heads (2) */
#define BPB_HiddSec 28	/* Number of special hidden sectors (4) */
#define BPB_TotSec32 32	/* Volume size [sector] (4) */
#define BS_DrvNum 36	/* Physical drive number (2) */
#define BS_BootSig 38	/* Extended boot signature (1) */
#define BS_VolID 39	/* Volume serial number (4) */
#define BS_VolLab 43	/* Volume label (8) */
#define BS_FilSysType 54	/* File system type (1) */
#define BPB_FATSz32 36	/* FAT size [sector] (4) */
#define BPB_ExtFlags 40	/* Extended flags (2) */
#define BPB_FSVer 42	/* File system version (2) */
#define BPB_RootClus 44	/* Root dir first cluster (4) */
#define BPB_FSInfo 48	/* Offset of FSInfo sector (2) */
#define BPB_BkBootSec 50	/* Offset of backup boot sector (2) */
#define BS_DrvNum32 64	/* Physical drive number (2) */
#define BS_BootSig32 66	/* Extended boot signature (1) */
#define BS_VolID32 67	/* Volume serial number (4) */
#define BS_VolLab32 71	/* Volume label (8) */
#define BS_FilSysType32 82	/* File system type (1) */
#define FSI_LeadSig 0	/* FSI: Leading signature (4) */
#define FSI_StrucSig 484	/* FSI: Structure signature (4) */
#define FSI_Free_Count 488	/* FSI: Number of free clusters (4) */
#define FSI_Nxt_Free 492	/* FSI: Last allocated cluster (4) */
#define MBR_Table 446	/* MBR: Partition table offset (2) */
#define SZ_PTE 16	/* MBR: Size of a partition table entry */
#define BS_55AA 510	/* Boot sector signature (2) */
#define DIR_Name 0	/* Short file name (11) */
#define DIR_Attr 11	/* Attribute (1) */
#define DIR_NTres 12	/* NT flag (1) */
#define DIR_CrtTimeTenth 13	/* Created time sub-second (1) */
#define DIR_CrtTime 14	/* Created time (2) */
#define DIR_CrtDate 16	/* Created date (2) */
#define DIR_LstAccDate 18	/* Last accessed date (2) */
#define DIR_FstClusHI 20	/* Higher 16-bit of first cluster (2) */
#define DIR_WrtTime 22	/* Modified time (2) */
#define DIR_WrtDate 24	/* Modified date (2) */
#define DIR_FstClusLO 26	/* Lower 16-bit of first cluster (2) */
#define DIR_FileSize 28	/* File size (4) */
#define LDIR_Ord 0	/* LFN entry order and LLE flag (1) */
#define LDIR_Attr 11	/* LFN attribute (1) */
#define LDIR_Type 12	/* LFN type (1) */
#define LDIR_Chksum 13	/* Sum of corresponding SFN entry */
#define LDIR_FstClusLO 26	/* Filled by zero (0) */
#define SZ_DIR 32		/* Size of a directory entry */
#define LLE 0x40	/* Last long entry flag in LDIR_Ord */
#define DDE 0xE5	/* Deleted directory entry mark in DIR_Name[0] */
#define NDDE 0x05	/* Replacement of the character collides with DDE */
#define DEF_NAMEBUF BYTE sfn[12]
#define INIT_BUF(dobj) (dobj).fn = sfn
#define FREE_BUF()
Functions
static void mem_cpy (void *dst, const void *src, UINT cnt)
static void mem_set (void *dst, int val, UINT cnt)
static int mem_cmp (const void *dst, const void *src, UINT cnt)
static int chk_chr (const char *str, int chr)
static FRESULT sync_window (FATFS *fs)
static FRESULT move_window (FATFS *fs, DWORD sector)
static FRESULT sync_fs (FATFS *fs)
DWORD clust2sect (FATFS *fs, DWORD clst)
DWORD get_fat (FATFS *fs, DWORD clst)
FRESULT put_fat (FATFS *fs, DWORD clst, DWORD val)
static FRESULT remove_chain (FATFS *fs, DWORD clst)
static DWORD create_chain (FATFS *fs, DWORD clst)
static FRESULT dir_sdi (DIR *dj, WORD idx)
static FRESULT dir_next (DIR *dj, int stretch)
static FRESULT dir_alloc (DIR *dj, UINT nent)
static DWORD ld_clust (FATFS *fs, BYTE *dir)
static void st_clust (BYTE *dir, DWORD cl)
static FRESULT dir_find (DIR *dj)
static FRESULT dir_read (DIR *dj, int vol)
static FRESULT dir_register (DIR *dj)
static FRESULT create_name (DIR *dj, const TCHAR **path)
static FRESULT follow_path (DIR *dj, const TCHAR *path)
static BYTE check_fs (FATFS *fs, DWORD sect)
static FRESULT chk_mounted (const TCHAR **path, FATFS **rfs, BYTE wmode)
static FRESULT validate (void *obj)
FRESULT f_mount (BYTE vol, FATFS *fs)
FRESULT f_open (FIL *fp, const TCHAR *path, BYTE mode)
FRESULT f_read (FIL *fp, void *buff, UINT btr, UINT *br)
FRESULT f_write (FIL *fp, const void *buff, UINT btw, UINT *bw)
FRESULT f_sync (FIL *fp)
FRESULT f_close (FIL *fp)
FRESULT f_lseek (FIL *fp, DWORD ofs)
FRESULT f_getlabel (const TCHAR *path, TCHAR *label, DWORD *sn)
FRESULT f_setlabel (const TCHAR *label)
Variables
static FATFS * FatFs [_VOLUMES]
static WORD Fsid
static const BYTE ExCvt [] = _EXCVT
Macro Definition Documentation
#define _DF1S 0
Referenced by create_name(), and f_setlabel().
#define _EXCVT
Value:
{0x80,0x9A,0x90,0x41,0x8E,0x41,0x8F,0x80,0x45,0x45,0x45,0x49,0x49,0x49,0x8E,0x8F,0x90,0x92,0x92,0x4F,0x99,
      0x4F,0x55,0x55,0x59,0x99,0x9A,0x9B,0x9C,0x9D,0x9E,0x9F, \
                                0x41,0x49,0x4F,0x55,0xA5,0xA5,0xA6,0xA7,0xA8,0xA9,0xAA,0xAB,0xAC,0x21,0xAE,
      0xAF,0xB0,0xB1,0xB2,0xB3,0xB4,0xB5,0xB6,0xB7,0xB8,0xB9,0xBA,0xBB,0xBC,0xBD,0xBE,0xBF, \
                                0xC0,0xC1,0xC2,0xC3,0xC4,0xC5,0xC6,0xC7,0xC8,0xC9,0xCA,0xCB,0xCC,0xCD,0xCE,
      0xCF,0xD0,0xD1,0xD2,0xD3,0xD4,0xD5,0xD6,0xD7,0xD8,0xD9,0xDA,0xDB,0xDC,0xDD,0xDE,0xDF, \
                                0xE0,0xE1,0xE2,0xE3,0xE4,0xE5,0xE6,0xE7,0xE8,0xE9,0xEA,0xEB,0xEC,0xED,0xEE,
      0xEF,0xF0,0xF1,0xF2,0xF3,0xF4,0xF5,0xF6,0xF7,0xF8,0xF9,0xFA,0xFB,0xFC,0xFD,0xFE,0xFF}
#define ABORT(fs, res) { fp->flag |= FA__ERROR; LEAVE_FF(fs, res); }
Referenced by f_lseek(), f_read(), and f_write().
#define BPB_BkBootSec 50	/* Offset of backup boot sector (2) */
#define BPB_BytsPerSec 11	/* Sector size [byte] (2) */
Referenced by chk_mounted().
#define BPB_ExtFlags 40	/* Extended flags (2) */
#define BPB_FATSz16 22	/* FAT size [sector] (2) */
Referenced by chk_mounted().
#define BPB_FATSz32 36	/* FAT size [sector] (4) */
Referenced by chk_mounted().
#define BPB_FSInfo 48	/* Offset of FSInfo sector (2) */
Referenced by chk_mounted().
#define BPB_FSVer 42	/* File system version (2) */
#define BPB_HiddSec 28	/* Number of special hidden sectors (4) */
#define BPB_Media 21	/* Media descriptor (1) */
#define BPB_NumFATs 16	/* Number of FAT copies (1) */
Referenced by chk_mounted().
#define BPB_NumHeads 26	/* Number of heads (2) */
#define BPB_RootClus 44	/* Root dir first cluster (4) */
Referenced by chk_mounted().
#define BPB_RootEntCnt 17	/* Number of root dir entries for FAT12/16 (2) */
Referenced by chk_mounted().
#define BPB_RsvdSecCnt 14	/* Size of reserved area [sector] (2) */
Referenced by chk_mounted().
#define BPB_SecPerClus 13	/* Cluster size [sector] (1) */
Referenced by chk_mounted().
#define BPB_SecPerTrk 24	/* Track size [sector] (2) */
#define BPB_TotSec16 19	/* Volume size [sector] (2) */
Referenced by chk_mounted().
#define BPB_TotSec32 32	/* Volume size [sector] (4) */
Referenced by chk_mounted().
#define BS_55AA 510	/* Boot sector signature (2) */
Referenced by check_fs(), chk_mounted(), and sync_fs().
#define BS_BootSig 38	/* Extended boot signature (1) */
#define BS_BootSig32 66	/* Extended boot signature (1) */
#define BS_DrvNum 36	/* Physical drive number (2) */
#define BS_DrvNum32 64	/* Physical drive number (2) */
#define BS_FilSysType 54	/* File system type (1) */
Referenced by check_fs().
#define BS_FilSysType32 82	/* File system type (1) */
Referenced by check_fs().
#define BS_jmpBoot 0	/* Jump instruction (3) */
#define BS_OEMName 3	/* OEM name (8) */
#define BS_VolID 39	/* Volume serial number (4) */
Referenced by f_getlabel().
#define BS_VolID32 67	/* Volume serial number (4) */
Referenced by f_getlabel().
#define BS_VolLab 43	/* Volume label (8) */
#define BS_VolLab32 71	/* Volume label (8) */
#define DDE 0xE5	/* Deleted directory entry mark in DIR_Name[0] */
Referenced by create_name(), dir_alloc(), dir_find(), dir_read(), and f_setlabel().
#define DEF_NAMEBUF BYTE sfn[12]
Referenced by f_open().
#define DIR_Attr 11	/* Attribute (1) */
Referenced by dir_find(), dir_read(), f_open(), f_setlabel(), f_sync(), and follow_path().
#define DIR_CrtDate 16	/* Created date (2) */
#define DIR_CrtTime 14	/* Created time (2) */
Referenced by f_open().
#define DIR_CrtTimeTenth 13	/* Created time sub-second (1) */
#define DIR_FileSize 28	/* File size (4) */
Referenced by f_open(), and f_sync().
#define DIR_FstClusHI 20	/* Higher 16-bit of first cluster (2) */
Referenced by ld_clust(), and st_clust().
#define DIR_FstClusLO 26	/* Lower 16-bit of first cluster (2) */
Referenced by ld_clust(), and st_clust().
#define DIR_LstAccDate 18	/* Last accessed date (2) */
Referenced by f_sync().
#define DIR_Name 0	/* Short file name (11) */
Referenced by dir_find(), and dir_read().
#define DIR_NTres 12	/* NT flag (1) */
Referenced by dir_register().
#define DIR_WrtDate 24	/* Modified date (2) */
#define DIR_WrtTime 22	/* Modified time (2) */
Referenced by f_setlabel(), and f_sync().
#define ENTER_FF(fs)
Referenced by chk_mounted(), and validate().
#define FREE_BUF()
Referenced by f_open().
#define FSI_Free_Count 488	/* FSI: Number of free clusters (4) */
Referenced by chk_mounted(), and sync_fs().
#define FSI_LeadSig 0	/* FSI: Leading signature (4) */
Referenced by chk_mounted(), and sync_fs().
#define FSI_Nxt_Free 492	/* FSI: Last allocated cluster (4) */
Referenced by chk_mounted(), and sync_fs().
#define FSI_StrucSig 484	/* FSI: Structure signature (4) */
Referenced by chk_mounted(), and sync_fs().
#define INIT_BUF(dobj) (dobj).fn = sfn
Referenced by f_open().
#define IsDBCS1(c) 0
Referenced by create_name(), f_getlabel(), and f_setlabel().
#define IsDBCS2(c) 0
Referenced by create_name(), f_getlabel(), and f_setlabel().
#define IsDigit(c) (((c)>='0')&&((c)<='9'))
#define IsLower(c) (((c)>='a')&&((c)<='z'))
Referenced by create_name(), and f_setlabel().
#define IsUpper(c) (((c)>='A')&&((c)<='Z'))
Referenced by create_name().
#define LDIR_Attr 11	/* LFN attribute (1) */
#define LDIR_Chksum 13	/* Sum of corresponding SFN entry */
Referenced by dir_find(), and dir_read().
#define LDIR_FstClusLO 26	/* Filled by zero (0) */
#define LDIR_Ord 0	/* LFN entry order and LLE flag (1) */
#define LDIR_Type 12	/* LFN type (1) */
#define LEAVE_FF(fs, res) return res
Referenced by f_close(), f_getlabel(), f_lseek(), f_open(), f_read(), f_setlabel(), f_sync(), and f_write().
#define LLE 0x40	/* Last long entry flag in LDIR_Ord */
#define MBR_Table 446	/* MBR: Partition table offset (2) */
Referenced by chk_mounted().
#define MIN_FAT16 4086	/* Minimum number of clusters for FAT16 */
Referenced by chk_mounted().
#define MIN_FAT32 65526	/* Minimum number of clusters for FAT32 */
Referenced by chk_mounted().
#define NDDE 0x05	/* Replacement of the character collides with DDE */
Referenced by create_name().
#define NS 11		/* Index of name status byte in fn[] */
Referenced by create_name(), dir_find(), dir_register(), and follow_path().
#define NS_BODY 0x08	/* Lower case flag (body) */
Referenced by create_name(), and dir_register().
#define NS_DOT 0x20	/* Dot entry */
Referenced by create_name(), dir_register(), and follow_path().
#define NS_EXT 0x10	/* Lower case flag (ext) */
Referenced by create_name(), and dir_register().
#define NS_LAST 0x04	/* Last segment */
Referenced by create_name(), and follow_path().
#define NS_LFN 0x02	/* Force to create LFN entry */
Referenced by create_name(), and dir_register().
#define NS_LOSS 0x01	/* Out of 8.3 format */
Referenced by create_name(), dir_find(), and dir_register().
#define SS(fs) 512U			/* Fixed sector size */
Referenced by chk_mounted(), dir_next(), dir_sdi(), f_lseek(), f_read(), f_write(), get_fat(), and put_fat().
#define SZ_DIR 32		/* Size of a directory entry */
Referenced by chk_mounted(), dir_next(), dir_register(), dir_sdi(), and f_setlabel().
#define SZ_PTE 16	/* MBR: Size of a partition table entry */
Referenced by chk_mounted().
Function Documentation
static BYTE check_fs (FATFS * fs, DWORD sect) [static]
References BS_55AA, BS_FilSysType, BS_FilSysType32, disk_read(), FATFS::drv, LD_DWORD, LD_WORD, RES_OK, and FATFS::win.
Referenced by chk_mounted().
static int chk_chr (const char * str, int chr) [static]
Referenced by create_name(), and f_setlabel().
static FRESULT chk_mounted (const TCHAR ** path, FATFS ** rfs, BYTE wmode) [static]
References _FS_READONLY, _VOLUMES, BPB_BytsPerSec, BPB_FATSz16, BPB_FATSz32, BPB_FSInfo, BPB_NumFATs, BPB_RootClus, BPB_RootEntCnt, BPB_RsvdSecCnt, BPB_SecPerClus, BPB_TotSec16, BPB_TotSec32, BS_55AA, check_fs(), FATFS::csize, FATFS::database, FATFS::dirbase, disk_initialize(), disk_ioctl(), disk_read(), disk_status(), FATFS::drv, ENTER_FF, FATFS::fatbase, FR_DISK_ERR, FR_INVALID_DRIVE, FR_NO_FILESYSTEM, FR_NOT_ENABLED, FR_NOT_READY, FR_OK, FR_WRITE_PROTECTED, FATFS::free_clust, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, FATFS::fsi_flag, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FATFS::fsi_sector, FSI_StrucSig, Fsid, FATFS::fsize, FATFS::id, FATFS::last_clust, LD2PD, LD2PT, LD_DWORD, LD_WORD, MBR_Table, MIN_FAT16, MIN_FAT32, FATFS::n_fatent, FATFS::n_fats, FATFS::n_rootdir, RES_OK, SS, STA_NOINIT, STA_PROTECT, SZ_DIR, SZ_PTE, FATFS::volbase, FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by f_getlabel(), f_open(), and f_setlabel().
DWORD clust2sect (FATFS * fs, DWORD clst)
References FATFS::csize, FATFS::database, and FATFS::n_fatent.
Referenced by dir_next(), dir_sdi(), f_lseek(), f_read(), f_write(), and remove_chain().
static DWORD create_chain (FATFS * fs, DWORD clst) [static]
References FR_DISK_ERR, FR_OK, FATFS::free_clust, FATFS::fsi_flag, get_fat(), FATFS::last_clust, FATFS::n_fatent, and put_fat().
Referenced by dir_next(), f_lseek(), and f_write().
static FRESULT create_name (DIR * dj, const TCHAR ** path) [static]
References _DF1S, _MAX_LFN, chk_chr(), DDE, ExCvt, DIR::fn, FR_INVALID_NAME, FR_OK, IsDBCS1, IsDBCS2, IsLower, IsUpper, mem_set(), NDDE, NS, NS_BODY, NS_DOT, NS_EXT, NS_LAST, NS_LFN, and NS_LOSS.
Referenced by follow_path().
static FRESULT dir_alloc (DIR * dj, UINT nent) [static]
References DDE, DIR::dir, dir_next(), dir_sdi(), FR_OK, DIR::fs, move_window(), and DIR::sect.
Referenced by dir_register(), and f_setlabel().
static FRESULT dir_find (DIR * dj) [static]
References AM_LFN, AM_MASK, AM_VOL, DDE, DIR::dir, DIR_Attr, DIR_Name, dir_next(), dir_sdi(), DIR::fn, FR_NO_FILE, FR_OK, DIR::fs, DIR::index, LDIR_Chksum, mem_cmp(), move_window(), NS, NS_LOSS, and DIR::sect.
Referenced by dir_register(), and follow_path().
static FRESULT dir_next (DIR * dj, int stretch) [static]
References DIR::clust, clust2sect(), create_chain(), FATFS::csize, DIR::dir, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_NO_FILE, FR_OK, DIR::fs, get_fat(), DIR::index, mem_set(), FATFS::n_fatent, FATFS::n_rootdir, DIR::sect, SS, sync_window(), SZ_DIR, FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by dir_alloc(), dir_find(), dir_read(), and dir_register().
static FRESULT dir_read (DIR * dj, int vol) [static]
References _FS_RPATH, AM_LFN, AM_MASK, AM_VOL, DDE, DIR::dir, DIR_Attr, DIR_Name, dir_next(), FR_NO_FILE, FR_OK, DIR::fs, DIR::index, LDIR_Chksum, move_window(), and DIR::sect.
Referenced by f_getlabel(), and f_setlabel().
static FRESULT dir_register (DIR * dj) [static]
References _FS_RPATH, DIR::dir, dir_alloc(), dir_find(), dir_next(), DIR_NTres, dir_sdi(), DIR::fn, FR_DENIED, FR_INVALID_NAME, FR_NO_FILE, FR_OK, DIR::fs, DIR::index, mem_cpy(), mem_set(), move_window(), NS, NS_BODY, NS_DOT, NS_EXT, NS_LFN, NS_LOSS, DIR::sect, SZ_DIR, and FATFS::wflag.
Referenced by f_open().
static FRESULT dir_sdi (DIR * dj, WORD idx) [static]
References DIR::clust, clust2sect(), FATFS::csize, DIR::dir, FATFS::dirbase, FR_DISK_ERR, FR_INT_ERR, FR_OK, DIR::fs, FS_FAT32, FATFS::fs_type, get_fat(), DIR::index, FATFS::n_fatent, FATFS::n_rootdir, DIR::sclust, DIR::sect, SS, SZ_DIR, and FATFS::win.
Referenced by dir_alloc(), dir_find(), dir_register(), f_getlabel(), f_setlabel(), and follow_path().
FRESULT f_close (FIL * fp)
References f_sync(), FR_OK, FIL::fs, LEAVE_FF, and validate().
Referenced by main().
FRESULT f_getlabel (const TCHAR * path, TCHAR * label, DWORD * sn)
References BS_VolID, BS_VolID32, chk_mounted(), DIR::dir, dir_read(), dir_sdi(), FR_NO_FILE, FR_OK, DIR::fs, FS_FAT32, FATFS::fs_type, IsDBCS1, IsDBCS2, LD_DWORD, LEAVE_FF, mem_cpy(), move_window(), DIR::sclust, FATFS::volbase, and FATFS::win.
Referenced by main().
FRESULT f_lseek (FIL * fp, DWORD ofs)
References _FS_READONLY, ABORT, FIL::clust, clust2sect(), create_chain(), CREATE_LINKMAP, FATFS::csize, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA__WRITTEN, FA_WRITE, FIL::flag, FIL::fptr, FR_DISK_ERR, FR_INT_ERR, FR_NOT_ENOUGH_CORE, FR_OK, FIL::fs, FIL::fsize, get_fat(), LEAVE_FF, FATFS::n_fatent, RES_OK, FIL::sclust, SS, and validate().
FRESULT f_mount (BYTE vol, FATFS * fs)
References _VOLUMES, FR_INT_ERR, FR_INVALID_DRIVE, FR_OK, and FATFS::fs_type.
Referenced by main().
FRESULT f_open (FIL * fp, const TCHAR * path, BYTE mode)
References AM_DIR, AM_RDO, chk_mounted(), DEF_NAMEBUF, DIR::dir, DIR_Attr, DIR_CrtTime, DIR_FileSize, FIL::dir_ptr, dir_register(), FIL::dir_sect, FIL::dsect, FA__WRITTEN, FA_CREATE_ALWAYS, FA_CREATE_NEW, FA_OPEN_ALWAYS, FA_READ, FA_WRITE, FIL::flag, follow_path(), FIL::fptr, FR_DENIED, FR_EXIST, FR_INT_ERR, FR_INVALID_NAME, FR_INVALID_OBJECT, FR_NO_FILE, FR_OK, FR_TOO_MANY_OPEN_FILES, FREE_BUF, FIL::fs, DIR::fs, FIL::fsize, get_fattime(), FATFS::id, FIL::id, INIT_BUF, FATFS::last_clust, ld_clust(), LD_DWORD, LEAVE_FF, move_window(), remove_chain(), FIL::sclust, st_clust(), ST_DWORD, FATFS::wflag, and FATFS::winsect.
Referenced by main().
FRESULT f_read (FIL * fp, void * buff, UINT btr, UINT * br)
References ABORT, FIL::clust, clust2sect(), FATFS::csize, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA_READ, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FIL::fs, FIL::fsize, get_fat(), LEAVE_FF, mem_cpy(), move_window(), RES_OK, FIL::sclust, SS, validate(), FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by main().
FRESULT f_setlabel (const TCHAR * label)
References _DF1S, AM_VOL, chk_chr(), chk_mounted(), DDE, DIR::dir, dir_alloc(), DIR_Attr, dir_read(), dir_sdi(), DIR_WrtTime, ExCvt, FR_INVALID_NAME, FR_NO_FILE, FR_OK, DIR::fs, get_fattime(), IsDBCS1, IsDBCS2, IsLower, LEAVE_FF, mem_cpy(), mem_set(), DIR::sclust, ST_DWORD, sync_fs(), SZ_DIR, and FATFS::wflag.
FRESULT f_sync (FIL * fp)
References AM_ARC, DIR_Attr, DIR_FileSize, DIR_LstAccDate, FIL::dir_ptr, FIL::dir_sect, DIR_WrtTime, disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__WRITTEN, FIL::flag, FR_DISK_ERR, FR_OK, FIL::fs, FIL::fsize, get_fattime(), LEAVE_FF, move_window(), RES_OK, FIL::sclust, st_clust(), ST_DWORD, ST_WORD, sync_fs(), validate(), and FATFS::wflag.
Referenced by f_close().
FRESULT f_write (FIL * fp, const void * buff, UINT btw, UINT * bw)
References ABORT, FIL::clust, clust2sect(), create_chain(), FATFS::csize, disk_read(), disk_write(), FATFS::drv, FIL::dsect, FA__DIRTY, FA__ERROR, FA__WRITTEN, FA_WRITE, FIL::flag, FIL::fptr, FR_DENIED, FR_DISK_ERR, FR_INT_ERR, FR_OK, FIL::fs, FIL::fsize, LEAVE_FF, mem_cpy(), move_window(), RES_OK, FIL::sclust, SS, sync_window(), validate(), FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by main().
static FRESULT follow_path (DIR * dj, const TCHAR * path) [static]
References _FS_RPATH, AM_DIR, create_name(), DIR::dir, DIR_Attr, dir_find(), dir_sdi(), DIR::fn, FR_NO_FILE, FR_NO_PATH, FR_OK, DIR::fs, ld_clust(), NS, NS_DOT, NS_LAST, and DIR::sclust.
Referenced by f_open().
DWORD get_fat (FATFS * fs, DWORD clst)
References FATFS::fatbase, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, LD_DWORD, LD_WORD, move_window(), FATFS::n_fatent, SS, and FATFS::win.
Referenced by create_chain(), dir_next(), dir_sdi(), f_lseek(), f_read(), and remove_chain().
static DWORD ld_clust (FATFS * fs, BYTE * dir) [static]
References DIR_FstClusHI, DIR_FstClusLO, FS_FAT32, FATFS::fs_type, and LD_WORD.
Referenced by f_open(), and follow_path().
static int mem_cmp (const void * dst, const void * src, UINT cnt) [static]
Referenced by dir_find().
static void mem_cpy (void * dst, const void * src, UINT cnt) [static]
Referenced by dir_register(), f_getlabel(), f_read(), f_setlabel(), and f_write().
static void mem_set (void * dst, int val, UINT cnt) [static]
Referenced by create_name(), dir_next(), dir_register(), f_setlabel(), and sync_fs().
static FRESULT move_window (FATFS * fs, DWORD sector) [static]
References disk_read(), FATFS::drv, FR_DISK_ERR, FR_OK, RES_OK, sync_window(), FATFS::win, and FATFS::winsect.
Referenced by dir_alloc(), dir_find(), dir_read(), dir_register(), f_getlabel(), f_open(), f_read(), f_sync(), f_write(), get_fat(), and put_fat().
FRESULT put_fat (FATFS * fs, DWORD clst, DWORD val)
References FATFS::fatbase, FR_INT_ERR, FR_OK, FS_FAT12, FS_FAT16, FS_FAT32, FATFS::fs_type, LD_DWORD, move_window(), FATFS::n_fatent, SS, ST_DWORD, ST_WORD, FATFS::wflag, and FATFS::win.
Referenced by create_chain(), and remove_chain().
static FRESULT remove_chain (FATFS * fs, DWORD clst) [static]
References clust2sect(), FATFS::csize, CTRL_ERASE_SECTOR, disk_ioctl(), FATFS::drv, FR_DISK_ERR, FR_INT_ERR, FR_OK, FATFS::free_clust, FATFS::fsi_flag, get_fat(), FATFS::n_fatent, and put_fat().
Referenced by f_open().
static void st_clust (BYTE * dir, DWORD cl) [static]
References DIR_FstClusHI, DIR_FstClusLO, and ST_WORD.
Referenced by f_open(), and f_sync().
static FRESULT sync_fs (FATFS * fs) [static]
References BS_55AA, CTRL_SYNC, disk_ioctl(), disk_write(), FATFS::drv, FR_DISK_ERR, FR_OK, FATFS::free_clust, FS_FAT32, FATFS::fs_type, FATFS::fsi_flag, FSI_Free_Count, FSI_LeadSig, FSI_Nxt_Free, FATFS::fsi_sector, FSI_StrucSig, FATFS::last_clust, mem_set(), RES_OK, ST_DWORD, ST_WORD, sync_window(), FATFS::win, and FATFS::winsect.
Referenced by f_setlabel(), and f_sync().
static FRESULT sync_window (FATFS * fs) [static]
References disk_write(), FATFS::drv, FATFS::fatbase, FR_DISK_ERR, FR_OK, FATFS::fsize, FATFS::n_fats, RES_OK, FATFS::wflag, FATFS::win, and FATFS::winsect.
Referenced by dir_next(), f_write(), move_window(), and sync_fs().
static FRESULT validate (void * obj) [static]
References disk_status(), FATFS::drv, ENTER_FF, FR_INVALID_OBJECT, FR_NOT_READY, FR_OK, FIL::fs, FATFS::fs_type, FATFS::id, FIL::id, and STA_NOINIT.
Referenced by f_close(), f_lseek(), f_read(), f_sync(), and f_write().
Variable Documentation
const BYTE ExCvt[] = _EXCVT [static]
Referenced by create_name(), and f_setlabel().
FATFS* FatFs[_VOLUMES] [static]
WORD Fsid [static]
Referenced by chk_mounted().