Content Management: Setters and Getters for order data
Setters and Getters for linkedList.
Functions
int getOrderId (struct order *orderData)
char getOrderStartstop (struct order *orderData, char bankNum)
int getOrderNote (struct order *orderData, char bankNum)
void setOrderId (struct order *orderData, int id)
void setOrderStartstop (struct order *orderData, char newStartstop, char bankNum)
void setOrderNote (struct order *orderData, char newNote, char bankNum)
Detailed Description
Setters and Getters for linkedList.
Function Documentation
int getOrderId (struct order * orderData)
References order::id.
Referenced by sort().
int getOrderNote (struct order * orderData, char bankNum)
References order::bank1_note, order::bank2_note, and order::bank3_note.
Referenced by main().
char getOrderStartstop (struct order * orderData, char bankNum)
References order::bank1_startstop, order::bank2_startstop, and order::bank3_startstop.
Referenced by main().
void setOrderId (struct order * orderData, int id)
References order::id.
void setOrderNote (struct order * orderData, char newNote, char bankNum)
References order::bank1_note, order::bank2_note, and order::bank3_note.
void setOrderStartstop (struct order * orderData, char newStartstop, char bankNum)
References order::bank1_startstop, order::bank2_startstop, and order::bank3_startstop.