sorting functions
Functions
void swap (struct onode **head, struct onode *n1, struct onode *n2)
void sort (struct onode **head)
Detailed Description
Function Documentation
void sort (struct onode ** head)
References onode::data, getNextOrder(), getOrderId(), getPrevOrder(), and swap().
Referenced by main().
void swap (struct onode ** head, struct onode * n1, struct onode * n2)
References onode::data.
Referenced by sort().