Content Management: Setters and Getters for linkedList
Setters and Getters for linkedList.
Functions
struct onode * getOrderNode (struct onode *head, int id)
In a linked list with *head as the head pointer, returns the onode with the given order id.
struct onode * getNextOrder (struct onode *order_node)
Simply returns the next node in the list, or NULL if there are no further nodes.
struct onode * getPrevOrder (struct onode *order_node)
struct order * getOrderData (struct onode *order_node)
Detailed Description
Setters and Getters for linkedList.
Function Documentation
struct onode* getNextOrder (struct onode * order_node)
Simply returns the next node in the list, or NULL if there are no further nodes.
References onode::next.
Referenced by sort().
struct order* getOrderData (struct onode * order_node)
References onode::data.
struct onode* getOrderNode (struct onode * head, int id)
In a linked list with *head as the head pointer, returns the onode with the given order id.
In a linked list with *head as the head pointer, returns the onode with the given order id.
If a node with the given word cannot be found, the function returns NULL.
References onode::data, order::id, and onode::next.
Referenced by main().
struct onode* getPrevOrder (struct onode * order_node)
References onode::prev.
Referenced by sort().