lcd8bit/lcd8bit.h File Reference
Functions
void lcd_set_write_instruction ()
void lcd_set_write_data ()
void lcd_write_byte (char c)
void lcd_clear_and_home ()
void lcd_home ()
void lcd_goto (uint8_t line, uint8_t pos)
void lcd_line_one ()
void lcd_line_two ()
void lcd_write_data (char c)
void lcd_write_string (char *x, uint8_t len)
void lcd_write_string_0 (char *x)
void lcd_write_string_p (const char *s)
void lcd_init ()
Function Documentation
void lcd_clear_and_home ()
References lcd_set_write_instruction(), and lcd_write_byte().
Referenced by die(), lcd_init(), and main().
void lcd_goto (uint8_t line, uint8_t pos)
References lcd_set_write_instruction(), and lcd_write_byte().
Referenced by lcd_line_one(), and lcd_line_two().
void lcd_home ()
References lcd_set_write_instruction(), and lcd_write_byte().
void lcd_init ()
References COMM_PORT, DATA_PORT, lcd_clear_and_home(), LCD_E, LCD_RS, and lcd_write_byte().
Referenced by main().
void lcd_line_one ()
References lcd_goto().
Referenced by die(), and main().
void lcd_line_two ()
References lcd_goto().
Referenced by die(), and main().
void lcd_set_write_data ()
References COMM_PORT, and LCD_RS.
Referenced by lcd_write_data().
void lcd_set_write_instruction ()
References COMM_PORT, and LCD_RS.
Referenced by lcd_clear_and_home(), lcd_goto(), and lcd_home().
void lcd_write_byte (char c)
References COMM_PORT, DATA_PORT, and LCD_E.
Referenced by lcd_clear_and_home(), lcd_goto(), lcd_home(), lcd_init(), and lcd_write_data().
void lcd_write_data (char c)
References lcd_set_write_data(), and lcd_write_byte().
Referenced by lcd_write_string(), lcd_write_string_0(), and lcd_write_string_p().
void lcd_write_string (char * x, uint8_t len)
References lcd_write_data().
void lcd_write_string_0 (char * x)
References lcd_write_data().
Referenced by die(), and main().
void lcd_write_string_p (const char * s)
References lcd_write_data().