lcd8bit/main.c File Reference
#include `config.h`
*
#include <avr/io.h>
*
#include <avr/pgmspace.h>
*
#include <util/delay.h>
*
#include <stdio.h>
*
#include `lcd8bit.h`
*
Functions
int main ()
Function Documentation
int main (void)
References lcd_clear_and_home(), lcd_init(), lcd_line_one(), lcd_line_two(), lcd_write_string_0(), and lcd_write_string_p().