list/list.h File Reference
Data Structures
struct order
struct onode
Functions
struct onode * newNode (struct order *data)
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
struct onode * newNodeByRef (struct order *data)
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
void pushNode (struct onode **head, struct onode *node)
In a linked list with *head as the head pointer, adds the given node to the front of the list.
struct onode * getOrderNode (struct onode *head, int id)
In a linked list with *head as the head pointer, returns the onode with the given order id.
void insertNode (struct onode **head, struct onode *prevNode, struct onode *insertingNode)
Insert the given node after the prevNode.
void evictNode (struct onode **head, struct onode *node)
Internally removes the specified node from the list, and updates the linked list.
void deleteNode (struct onode **head, struct onode *node)
Removes the specified node from the list, and frees all memory the node is using.
void deleteNodeOnly (struct onode **head, struct onode *node)
Removes the specified node from the list, and does NOT free memory the node is using.
void deleteList (struct onode **head)
Deletes every node in the list with *head as the head pointer.
void deleteJustList (struct onode **head)
Deletes every node EXCEPT the head in the list with *head as the head pointer.
void printList (struct onode *node, void(*printItem)(struct order *, FILE *), FILE *out)
group1 Content Management: Setters and Getters for linkedList
Setters and Getters for linkedList
struct onode * getNextOrder (struct onode *order_node)
Simply returns the next node in the list, or NULL if there are no further nodes.
struct onode * getPrevOrder (struct onode *order_node)
struct order * getOrderData (struct onode *order_node)
group2 Content Management: Setters and Getters for order data
Setters and Getters for linkedList
int getOrderId (struct order *orderData)
char getOrderStartstop (struct order *orderData, char bankNum)
int getOrderNote (struct order *orderData, char bankNum)
void setOrderId (struct order *orderData, int id)
void setOrderStartstop (struct order *orderData, char newStartstop, char bankNum)
void setOrderNote (struct order *orderData, char newNote, char bankNum)
group3 Sorting functions
void swap (struct onode **head, struct onode *n1, struct onode *n2)
void sort (struct onode **head)
Performes insertion sort on the list by comparing the OrderID.
Function Documentation
void deleteJustList (struct onode ** head)
Deletes every node EXCEPT the head in the list with *head as the head pointer.
After calling this function, all memory used by the list should be freed, and *head should be NULL.
References onode::next.
void deleteList (struct onode ** head)
Deletes every node in the list with *head as the head pointer.
After calling this function, all memory used by the list should be freed, and *head should be NULL.
References onode::data, and onode::next.
void deleteNode (struct onode ** head, struct onode * node)
Removes the specified node from the list, and frees all memory the node is using.
Remember if *head is the node being deleted, it must be updated.
References onode::data, and deleteNodeOnly().
void deleteNodeOnly (struct onode ** head, struct onode * node)
Removes the specified node from the list, and does NOT free memory the node is using.
Remember if *head is the node being deleted, it must be updated.
References evictNode().
Referenced by deleteNode().
void evictNode (struct onode ** head, struct onode * node)
Internally removes the specified node from the list, and updates the linked list.
References onode::next, and onode::prev.
Referenced by deleteNodeOnly().
struct onode* getNextOrder (struct onode * order_node)
Simply returns the next node in the list, or NULL if there are no further nodes.
References onode::next.
Referenced by sort().
struct order* getOrderData (struct onode * order_node)
References onode::data.
int getOrderId (struct order * orderData)
References order::id.
Referenced by sort().
struct onode* getOrderNode (struct onode * head, int id)
In a linked list with *head as the head pointer, returns the onode with the given order id.
In a linked list with *head as the head pointer, returns the onode with the given order id.
If a node with the given word cannot be found, the function returns NULL.
References onode::data, order::id, and onode::next.
int getOrderNote (struct order * orderData, char bankNum)
References order::bank1_note, order::bank2_note, and order::bank3_note.
char getOrderStartstop (struct order * orderData, char bankNum)
References order::bank1_startstop, order::bank2_startstop, and order::bank3_startstop.
struct onode* getPrevOrder (struct onode * order_node)
References onode::prev.
Referenced by sort().
void insertNode (struct onode ** head, struct onode * prevNode, struct onode * insertingNode)
Insert the given node after the prevNode.
If the prevNode is NULL, then the given node is inserted at the head of the list.
References onode::next, onode::prev, and pushNode().
struct onode* newNode (struct order * data)
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
If you are implementing this function make sure that you duplicate, as the original data may be modified by the calling function.
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
The order is copied into the node as a new instance.
References order::bank1_note, order::bank1_startstop, order::bank2_note, order::bank2_startstop, order::bank3_note, order::bank3_startstop, g, and order::id.
Referenced by main().
struct onode* newNodeByRef (struct order * data)
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
This function is different that newNode in that the new node is created by reference and not copied
Returns a new linked list node filled in with the given order, The function allocates a new order and copy the values stored in data then allocate a linked list node.
The order is inserted by reference.
References onode::data.
void printList (struct onode * node, void(*)(struct order *, FILE *) printItem, FILE * out)
References onode::data, and onode::next.
void pushNode (struct onode ** head, struct onode * node)
In a linked list with *head as the head pointer, adds the given node to the front of the list.
References onode::next, and onode::prev.
Referenced by insertNode(), and main().
void setOrderId (struct order * orderData, int id)
References order::id.
void setOrderNote (struct order * orderData, char newNote, char bankNum)
References order::bank1_note, order::bank2_note, and order::bank3_note.
void setOrderStartstop (struct order * orderData, char newStartstop, char bankNum)
References order::bank1_startstop, order::bank2_startstop, and order::bank3_startstop.
void sort (struct onode ** head)
Performes insertion sort on the list by comparing the OrderID.
Sorts from largest(head) to smallest.
References onode::data, getNextOrder(), getOrderId(), getPrevOrder(), and swap().
Referenced by main().
void swap (struct onode ** head, struct onode * n1, struct onode * n2)
References onode::data.
Referenced by sort().