sd_card/main.c File Reference
#include <avr/io.h>
*
#include `timeout.h`
*
#include <util/delay.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `ff.h`
*
#include `integer.h`
*
Functions
DWORD get_fattime (void)
int main (void)
Variables
FATFS FatFs
FIL * fp
Function Documentation
DWORD get_fattime (void)
int main (void)
References f_close(), f_getlabel(), f_lseek(), f_mount(), f_open(), f_read(), f_size, f_write(), FA_CREATE_ALWAYS, FA_OPEN_ALWAYS, FA_READ, FA_WRITE, and FR_OK.
Variable Documentation
FATFS FatFs
FIL* fp