sd_card/sdmm.c File Reference
#include `diskio.h`
*
#include <avr/io.h>
*
Macros
#define SD_COM_PORT PORTA
#define DO_INIT() /* Initialize port MMC DO as input */
#define DO_DQ 3
#define DO (SD_COM_PORT.IN &	(1<<DO_DQ))	/* Test for MMC DO ('H':true, 'L':false) */
#define DI_DQ 6
#define DI_INIT() SD_COM_PORT.DIRSET |= (1<<DI_DQ)	/* Initialize port MMC DI as output */
#define DI_H() SD_COM_PORT.OUT |= (1<<DI_DQ)	/* Set MMC DI `high` */
#define DI_L() SD_COM_PORT.OUT &= ~(1<<DI_DQ)	/* Set MMC DI `low` */
#define CK_DQ 4
#define CK_INIT() SD_COM_PORT.DIRSET |= (1<<CK_DQ)	/* Initialize port MMC SCLK as output */
#define CK_H() SD_COM_PORT.OUT |= (1<<CK_DQ)	/* Set MMC SCLK `high` */
#define CK_L() SD_COM_PORT.OUT &= ~(1<<CK_DQ)	/* Set MMC SCLK `low` */
#define CS_DQ 5
#define CS_INIT() SD_COM_PORT.DIRSET |= (1<<CS_DQ)	/* Initialize port MMC CS as output */
#define CS_H() SD_COM_PORT.OUT |= (1<<CS_DQ)	/* Set MMC CS `high` */
#define CS_L() SD_COM_PORT.OUT &= ~(1<<CS_DQ)	/* Set MMC CS `low` */
#define CMD0 (0)			/* GO_IDLE_STATE */
#define CMD1 (1)			/* SEND_OP_COND */
#define ACMD41 (0x80+41)	/* SEND_OP_COND (SDC) */
#define CMD8 (8)			/* SEND_IF_COND */
#define CMD9 (9)			/* SEND_CSD */
#define CMD10 (10)		/* SEND_CID */
#define CMD12 (12)		/* STOP_TRANSMISSION */
#define CMD13 (13)		/* SEND_STATUS */
#define ACMD13 (0x80+13)	/* SD_STATUS (SDC) */
#define CMD16 (16)		/* SET_BLOCKLEN */
#define CMD17 (17)		/* READ_SINGLE_BLOCK */
#define CMD18 (18)		/* READ_MULTIPLE_BLOCK */
#define CMD23 (23)		/* SET_BLOCK_COUNT */
#define ACMD23 (0x80+23)	/* SET_WR_BLK_ERASE_COUNT (SDC) */
#define CMD24 (24)		/* WRITE_BLOCK */
#define CMD25 (25)		/* WRITE_MULTIPLE_BLOCK */
#define CMD32 (32)		/* ERASE_ER_BLK_START */
#define CMD33 (33)		/* ERASE_ER_BLK_END */
#define CMD38 (38)		/* ERASE */
#define CMD55 (55)		/* APP_CMD */
#define CMD58 (58)		/* READ_OCR */
Functions
static void dly_us (UINT n)
static void xmit_mmc (const BYTE *buff, UINT bc)
static void rcvr_mmc (BYTE *buff, UINT bc)
static int wait_ready (void)
static void deselect (void)
static int select (void)
static int rcvr_datablock (BYTE *buff, UINT btr)
static int xmit_datablock (const BYTE *buff, BYTE token)
static BYTE send_cmd (BYTE cmd, DWORD arg)
DSTATUS disk_status (BYTE drv)
DSTATUS disk_initialize (BYTE drv)
DRESULT disk_read (BYTE drv, BYTE *buff, DWORD sector, BYTE count)
DRESULT disk_write (BYTE drv, const BYTE *buff, DWORD sector, BYTE count)
DRESULT disk_ioctl (BYTE drv, BYTE ctrl, void *buff)
Variables
static DSTATUS Stat = STA_NOINIT
static BYTE CardType
Macro Definition Documentation
#define ACMD13 (0x80+13)	/* SD_STATUS (SDC) */
#define ACMD23 (0x80+23)	/* SET_WR_BLK_ERASE_COUNT (SDC) */
Referenced by disk_write().
#define ACMD41 (0x80+41)	/* SEND_OP_COND (SDC) */
Referenced by disk_initialize().
#define CK_DQ 4
#define CK_H() SD_COM_PORT.OUT |= (1<<CK_DQ)	/* Set MMC SCLK `high` */
Referenced by rcvr_mmc(), and xmit_mmc().
#define CK_INIT() SD_COM_PORT.DIRSET |= (1<<CK_DQ)	/* Initialize port MMC SCLK as output */
Referenced by disk_initialize().
#define CK_L() SD_COM_PORT.OUT &= ~(1<<CK_DQ)	/* Set MMC SCLK `low` */
Referenced by disk_initialize(), rcvr_mmc(), and xmit_mmc().
#define CMD0 (0)			/* GO_IDLE_STATE */
Referenced by disk_initialize(), and send_cmd().
#define CMD1 (1)			/* SEND_OP_COND */
Referenced by disk_initialize().
#define CMD10 (10)		/* SEND_CID */
#define CMD12 (12)		/* STOP_TRANSMISSION */
Referenced by disk_read(), and send_cmd().
#define CMD13 (13)		/* SEND_STATUS */
#define CMD16 (16)		/* SET_BLOCKLEN */
Referenced by disk_initialize().
#define CMD17 (17)		/* READ_SINGLE_BLOCK */
Referenced by disk_read().
#define CMD18 (18)		/* READ_MULTIPLE_BLOCK */
Referenced by disk_read().
#define CMD23 (23)		/* SET_BLOCK_COUNT */
#define CMD24 (24)		/* WRITE_BLOCK */
Referenced by disk_write().
#define CMD25 (25)		/* WRITE_MULTIPLE_BLOCK */
Referenced by disk_write().
#define CMD32 (32)		/* ERASE_ER_BLK_START */
#define CMD33 (33)		/* ERASE_ER_BLK_END */
#define CMD38 (38)		/* ERASE */
#define CMD55 (55)		/* APP_CMD */
Referenced by send_cmd().
#define CMD58 (58)		/* READ_OCR */
Referenced by disk_initialize().
#define CMD8 (8)			/* SEND_IF_COND */
Referenced by disk_initialize(), and send_cmd().
#define CMD9 (9)			/* SEND_CSD */
Referenced by disk_ioctl().
#define CS_DQ 5
#define CS_H() SD_COM_PORT.OUT |= (1<<CS_DQ)	/* Set MMC CS `high` */
Referenced by deselect(), and disk_initialize().
#define CS_INIT() SD_COM_PORT.DIRSET |= (1<<CS_DQ)	/* Initialize port MMC CS as output */
Referenced by disk_initialize().
#define CS_L() SD_COM_PORT.OUT &= ~(1<<CS_DQ)	/* Set MMC CS `low` */
Referenced by select().
#define DI_DQ 6
#define DI_H() SD_COM_PORT.OUT |= (1<<DI_DQ)	/* Set MMC DI `high` */
Referenced by rcvr_mmc(), and xmit_mmc().
#define DI_INIT() SD_COM_PORT.DIRSET |= (1<<DI_DQ)	/* Initialize port MMC DI as output */
Referenced by disk_initialize().
#define DI_L() SD_COM_PORT.OUT &= ~(1<<DI_DQ)	/* Set MMC DI `low` */
Referenced by xmit_mmc().
#define DO (SD_COM_PORT.IN &	(1<<DO_DQ))	/* Test for MMC DO ('H':true, 'L':false) */
Referenced by rcvr_mmc().
#define DO_DQ 3
#define DO_INIT() /* Initialize port MMC DO as input */
Referenced by disk_initialize().
#define SD_COM_PORT PORTA
Referenced by dly_us().
Function Documentation
static void deselect (void) [static]
References CS_H, and rcvr_mmc().
Referenced by disk_initialize(), disk_ioctl(), disk_read(), disk_write(), select(), and send_cmd().
DSTATUS disk_initialize (BYTE drv)
References ACMD41, CardType, CK_INIT, CK_L, CMD0, CMD1, CMD16, CMD58, CMD8, CS_H, CS_INIT, CT_BLOCK, CT_MMC, CT_SD1, CT_SD2, deselect(), DI_INIT, dly_us(), DO_INIT, rcvr_mmc(), RES_NOTRDY, send_cmd(), STA_NOINIT, and Stat.
Referenced by chk_mounted().
DRESULT disk_ioctl (BYTE drv, BYTE ctrl, void * buff)
References CMD9, CTRL_SYNC, deselect(), disk_status(), GET_BLOCK_SIZE, GET_SECTOR_COUNT, rcvr_datablock(), RES_ERROR, RES_NOTRDY, RES_OK, RES_PARERR, select(), send_cmd(), and STA_NOINIT.
Referenced by chk_mounted(), remove_chain(), and sync_fs().
DRESULT disk_read (BYTE drv, BYTE * buff, DWORD sector, BYTE count)
References CardType, CMD12, CMD17, CMD18, CT_BLOCK, deselect(), disk_status(), rcvr_datablock(), RES_ERROR, RES_NOTRDY, RES_OK, send_cmd(), and STA_NOINIT.
Referenced by check_fs(), chk_mounted(), f_lseek(), f_read(), f_write(), and move_window().
DSTATUS disk_status (BYTE drv)
References STA_NOINIT, and Stat.
Referenced by chk_mounted(), disk_ioctl(), disk_read(), disk_write(), and validate().
DRESULT disk_write (BYTE drv, const BYTE * buff, DWORD sector, BYTE count)
References ACMD23, CardType, CMD24, CMD25, CT_BLOCK, CT_SDC, deselect(), disk_status(), RES_ERROR, RES_NOTRDY, RES_OK, send_cmd(), STA_NOINIT, and xmit_datablock().
Referenced by f_lseek(), f_read(), f_sync(), f_write(), sync_fs(), and sync_window().
static void dly_us (UINT n) [static]
References SD_COM_PORT.
Referenced by disk_initialize(), rcvr_datablock(), and wait_ready().
static int rcvr_datablock (BYTE * buff, UINT btr) [static]
References dly_us(), and rcvr_mmc().
Referenced by disk_ioctl(), and disk_read().
static void rcvr_mmc (BYTE * buff, UINT bc) [static]
References CK_H, CK_L, DI_H, and DO.
Referenced by deselect(), disk_initialize(), rcvr_datablock(), select(), send_cmd(), wait_ready(), and xmit_datablock().
static int select (void) [static]
References CS_L, deselect(), rcvr_mmc(), and wait_ready().
Referenced by disk_ioctl(), and send_cmd().
static BYTE send_cmd (BYTE cmd, DWORD arg) [static]
References CMD0, CMD12, CMD55, CMD8, deselect(), rcvr_mmc(), select(), and xmit_mmc().
Referenced by disk_initialize(), disk_ioctl(), disk_read(), and disk_write().
static int wait_ready (void) [static]
References dly_us(), and rcvr_mmc().
Referenced by select(), and xmit_datablock().
static int xmit_datablock (const BYTE * buff, BYTE token) [static]
References rcvr_mmc(), wait_ready(), and xmit_mmc().
Referenced by disk_write().
static void xmit_mmc (const BYTE * buff, UINT bc) [static]
References CK_H, CK_L, DI_H, and DI_L.
Referenced by send_cmd(), and xmit_datablock().
Variable Documentation
BYTE CardType [static]
Referenced by disk_initialize(), disk_read(), and disk_write().
DSTATUS Stat = STA_NOINIT [static]
Referenced by disk_initialize(), and disk_status().