wavegen/wavegen.h File Reference
#include <stdint.h>
*
#include <avr/interrupt.h>
*
#include <avr/io.h>
*
#include <util/delay.h>
*
#include <avr/pgmspace.h>
*
#include <stdlib.h>
*
Macros
#define INTERRUPT_PERIOD 512
#define FINT (F_CPU / INTERRUPT_PERIOD)
#define FS (FINT)
Functions
void wavegen_pwmInit ()
Sets up the hardware PWM in the XMEGA.
void wavegen_clock_init (void)
Sets up the internal oscillator in the XMEGA.
void wavegen_pwmSet (char channel, int value)
Sets the PWM frequency per channel.
void wavegen_sineWave (char wavetableNum)
Copies a sinewave from the program memory into the buffer.
void wavegen_noiseWave (char wavetableNum)
Copies a noise sample into the buffer.
void wavegen_setFrequency2 (unsigned int freq)
void wavegen_setFrequency (unsigned int freq)
void wavegen_setSound (char startStop, char bankNum)
Will set the specific bank (1,2,3) to be enabled or disabled.
void wavegen_disableSound (char bankNum)
Copies a noise sample into the buffer.
Macro Definition Documentation
#define FINT (F_CPU / INTERRUPT_PERIOD)
#define FS (FINT)
#define INTERRUPT_PERIOD 512
Function Documentation
void wavegen_clock_init (void)
Sets up the internal oscillator in the XMEGA.
Sets the internal oscillator to 32Mhz and waits until the ooscillator is stable.
Referenced by main().
void wavegen_disableSound (char bankNum)
Copies a noise sample into the buffer.
References sound1Enabled, sound2Enabled, and sound3Enabled.
void wavegen_noiseWave (char wavetableNum)
Copies a noise sample into the buffer.
References wavetable, wavetable2, and wavetable3.
Referenced by main().
void wavegen_pwmInit ()
Sets up the hardware PWM in the XMEGA.
Referenced by main().
void wavegen_pwmSet (char channel, int value)
Sets the PWM frequency per channel.
Channels are 0,1,2.
Referenced by ISR().
void wavegen_setFrequency (unsigned int freq)
References F_CPU, frequencyCoef, FS, and soundPWM.
Referenced by main().
void wavegen_setFrequency2 (unsigned int freq)
References F_CPU, frequencyCoef2, FS, and soundPWM.
Referenced by main().
void wavegen_setSound (char startStop, char bankNum)
Will set the specific bank (1,2,3) to be enabled or disabled.
startStop designates enabled.
References sound1Enabled, sound2Enabled, and sound3Enabled.
Referenced by main().
void wavegen_sineWave (char wavetableNum)
Copies a sinewave from the program memory into the buffer.
References wavetable, wavetable2, and wavetable3.
Referenced by main().