wavegen/~main.c File Reference
#include <stdint.h>
*
#include <avr/interrupt.h>
*
#include <avr/io.h>
*
#include <util/delay.h>
*
#include <avr/pgmspace.h>
*
Macros
#define F_CPU 32000000UL
#define INTERRUPT_PERIOD 512
#define FINT (F_CPU / INTERRUPT_PERIOD)
#define FS (FINT)
Functions
void pwmSet (char channel, int value)
void sineWave ()
void setFrequency2 ()
void setFrequency ()
int main ()
ISR (TCC0_CCA_vect)
ISR (TCC0_CCB_vect)
void noiseWave ()
void pwmInit ()
void setFrequency (unsigned int freq)
void setFrequency2 (unsigned int freq)
void clock_init (void)
Variables
const unsigned char sinetable[256] PROGMEM
unsigned char wavetable [256]
unsigned int frequencyCoef =100
unsigned int frequencyCoef2 =100
char soundEnabled =1
char soundPWM =1
char soundOn =0
int currentVoice =0
Macro Definition Documentation
#define F_CPU 32000000UL
Referenced by setFrequency(), and setFrequency2().
#define FINT (F_CPU / INTERRUPT_PERIOD)
#define FS (FINT)
Referenced by setFrequency(), and setFrequency2().
#define INTERRUPT_PERIOD 512
Function Documentation
void clock_init (void)
Referenced by main().
ISR (TCC0_CCA_vect)
References frequencyCoef, pwmSet(), soundPWM, and wavetable.
ISR (TCC0_CCB_vect)
References frequencyCoef2, pwmSet(), soundPWM, and wavetable.
int main ()
References clock_init(), pwmInit(), setFrequency(), and setFrequency2().
void noiseWave ()
References wavetable.
void pwmInit ()
References sineWave().
Referenced by main().
void pwmSet (char channel, int value)
Referenced by ISR().
void setFrequency ()
Referenced by main().
void setFrequency (unsigned int freq)
References F_CPU, frequencyCoef, FS, and soundPWM.
void setFrequency2 ()
Referenced by main().
void setFrequency2 (unsigned int freq)
References F_CPU, frequencyCoef2, FS, and soundPWM.
void sineWave ()
References wavetable.
Referenced by pwmInit().
Variable Documentation
int currentVoice =0
unsigned int frequencyCoef =100
Referenced by ISR(), and setFrequency().
unsigned int frequencyCoef2 =100
Referenced by ISR(), and setFrequency2().
const unsigned char sinetable [256] PROGMEM
Initial value:
= {
,131,134,137,140,143,146,149,152,156,159,162,165,168,171,174,
,179,182,185,188,191,193,196,199,201,204,206,209,211,213,216,
,220,222,224,226,228,230,232,234,236,237,239,240,242,243,245,
,247,248,249,250,251,252,252,253,254,254,255,255,255,255,255,
,255,255,255,255,255,254,254,253,252,252,251,250,249,248,247,
,245,243,242,240,239,237,236,234,232,230,228,226,224,222,220,
,216,213,211,209,206,204,201,199,196,193,191,188,185,182,179,
,174,171,168,165,162,159,156,152,149,146,143,140,137,134,131,
,124,121,118,115,112,109,106,103,99, 96, 93, 90, 87, 84, 81,
, 76, 73, 70, 67, 64, 62, 59, 56, 54, 51, 49, 46, 44, 42, 39,
, 35, 33, 31, 29, 27, 25, 23, 21, 19, 18, 16, 15, 13, 12, 10,
, 8, 7, 6, 5, 4, 3, 3, 2, 1, 1, 0, 0, 0, 0, 0,
, 0, 0, 0, 0, 0, 1, 1, 2, 3, 3, 4, 5, 6, 7, 8,
, 10, 12, 13, 15, 16, 18, 19, 21, 23, 25, 27, 29, 31, 33, 35,
, 39, 42, 44, 46, 49, 51, 54, 56, 59, 62, 64, 67, 70, 73, 76,
, 81, 84, 87, 90, 93, 96, 99, 103,106,109,112,115,118,121,124
}
char soundEnabled =1
char soundOn =0
char soundPWM =1
Referenced by ISR(), setFrequency(), and setFrequency2().
unsigned char wavetable[256]
Referenced by ISR(), noiseWave(), and sineWave().